services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/site
      - jekyll_cache:/site/.jekyll-cache
      - jekyll_metadata:/site/.jekyll-metadata
      - bundle_cache:/usr/local/bundle   # 👈 AÑADE ESTO
    environment:
      - JEKYLL_ENV=development
    command: >
      sh -c "
        bundle check || bundle install &&
        python3 caducidad.py &&
        python3 calfile.py &&
        bundle exec jekyll serve --host 0.0.0.0 --port 4000 --watch --livereload --force_polling
      "

volumes:
  jekyll_cache:
  jekyll_metadata:
  bundle_cache: